### ISSUE TITLE
output.tsv conformal

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#101]
When building a model with conformal, the output does not print c0 and c1, and only print ymatrix. By the way, where are the yadjusted values?? I would add another column where it says out of domain if this compound can not be predicted.

**Comment by kpinto-gil** [comment]
terminal output format:
- could we eliminate the arrows '>>'
- build and external predict does not mach the order (see conformal_coverage and coverage)

build:
>>      nobj  ( number of objects ) :  584.0
>>      nvarx  ( number of predictor variables ) :  111.0
>>      model  ( model type ) :  RF qualitative (optimized)
>>      model  ( model type ) :  conformal RF qualitative
>>      TP  ( True positives in cross-validation ) :  11.0
>>      TN  ( True negatives in cross-validation ) :  10.0
>>      FP  ( False positives in cross-validation ) :  0.0
>>      FN  ( False negatives in cross-validation ) :  1.0
>>      Sensitivity  ( Sensitivity in cross-validation ) :  0.9167
>>      Specificity  ( Specificity in cross-validation ) :  1.0
>>      MCC  ( Matthews Correlation Coefficient in cross-validation ) :  0.9129
**>>      Conformal_coverage  ( Conformal coverage ) :  0.7097**
>>      Conformal_accuracy  ( Conformal accuracy ) :  0.9545

predict:

>>      obj_num  ( number of objects ) :  147.0
>>      TP  ( True positives in external-validation ) :  8.0
>>      TN  ( True negatives in external-validation ) :  64.0
>>      FP  ( False positives in external-validation ) :  17.0
>>      FN  ( False negatives in external-validation ) :  1.0
**>>      Coverage  ( Conformal coverage in external-validation ) :  0.6122**
>>      Sensitivity  ( Sensitivity in external-validation ) :  0.8889
>>      Specificity  ( Specificity in external-validation ) :  0.7901
>>      MCC  ( Mattews Correlation Coefficient in external-validation ) :  0.4548

**Comment by kpinto-gil** [comment]
As a suggestion: wouldn't it be better to use a pandas dataframe instead of print statements in the code to show the final result in terminal?? I would also appreciate if we could save this dataframe in pickle, tsv, .. format.

**Comment by manuelpastor** [comment]
Results are already written to a pickl and are fully accessible as JSON. The output can also be dump to a TSV. I think pandas dataframes were not designed to show output, please provide more information if you don't agree

**Comment by manuelpastor** [comment]
Yes, they can be printed as any Python type do. What is the advantage? Showing the labels? That's true for matrix data but in this case we have a dictionary!. I keep thinking there is no advantage with respect 
printing key and value (formated as needed)
