### ISSUE TITLE
'action_report' missing info

### ISSUE THREAD

**Issue by Javimuca** [phi-grib/flame#107]
It would have to return the information of each version for each model, in addition to the models that do not have results yet, that is, the development version, even if it is empty, so that it appears in the model table and can be selected for further construction.

**Comment by manuelpastor** [comment]
action report has been completelly rebuilt. Now it returns a JSON with an structure like this

```
 [  # list of models
    ['CACO2'.
        [ # list of versions
           [ 0,
             [ # list of information items ]
           ],
           [1,
 ....
 
```
