### ISSUE TITLE
Use builtin types in returns and not json

### ISSUE THREAD

**Issue by BielStela** [phi-grib/flame#121]
Now some functions like `action_info` and `predict.run` return a JSON like string directly from the function call. It would be cleaner if those functions return a normal dict or any builtin collection type instead and the API then serializes it to JSON with whatever structure is necessary. 
Making flame returning json like string is mixing functionalities between the API (adapter) and the library.

**Comment by manuelpastor** [comment]
Agreed..

**Comment by manuelpastor** [comment]
Implemented
