### ISSUE TITLE
Parameter for Scaling with StandardScaler

### ISSUE THREAD

**Issue by ChrisHill8** [phi-grib/flame#122]
### Feature Request: Scaling with sklearn StandardScaler

When building a model I'd like to have the option to use the sklearn StandardScaler, MinMaxScaler or no scaling at all. Could you include this option as parameter?

**Comment by manuelpastor** [comment]
Thanks for the suggestion. It was been added to the new features list

**Comment by manuelpastor** [comment]
It is now implemented!
