### ISSUE TITLE
Imbalance data method not recognized

### ISSUE THREAD

**Issue by ChrisHill8** [phi-grib/flame#123]
I tried to build a classification model with `flame -c build -e BSEP -f BSEP_flame.sdf -p parameters.yaml`
In the model settings of the parameters file `quantitative: false`

This results in the error: `Error initializing BaseEstimator parentclass with exception: Imbalance data method not recognized`

![imbalance_data_method](https://user-images.githubusercontent.com/44038602/54265070-c1b68d00-4574-11e9-89cb-f267cf9b13c9.png)

PS: Building the model with the same command and parameters file, except `quantitative: true` works

**Comment by ChrisHill8** [comment]
Problem was caused by the changes to the format of the parameter file.

Using a parameter file exactly like the new format given by `flame -c manage -e MY_MODEL -a parameters` and only changing the options worked.

**Comment by manuelpastor** [comment]
The problem has been fixed
