### ISSUE TITLE
Inconsistency between command line and web service

### ISSUE THREAD

**Issue by ChrisHill8** [phi-grib/flame#127]
Very minor, but easy to fix and maybe worth changing having consistency in mind:
When exporting predictions from the command line as TSV the class labels True and False start with an uppercase letter. The webservice exports them in lowercase.
Also the first column is either called obj_nam (CL) or obj nam (WS)

**Comment by manuelpastor** [comment]
We consider not important the consistence between these two formats. The use of lowercases or the removal of the underscore tried to make more readable the web output
