### ISSUE TITLE
Flame commands suggestion

### ISSUE THREAD

**Issue by ChrisHill8** [phi-grib/flame#129]
To me the -c command seems a bit unnecessary, as _build_, _config_ and _predict_ could be an action (-a) command as well.
I don't see a use case where -a and -c arguments overlap, so I'd remove the -c command and make every -c option an action instead (except manage, which is no longer needed).

This of course is a personal opinion and I don't have any insight on what's planned for the future.

**Comment by manuelpastor** [comment]
The whole application has been designed around these three tasks: manage, build and predict, which also influenced the code organization. For consistency we prefer to keep them grouped as they are
