### ISSUE TITLE
Random_state None not working

### ISSUE THREAD

**Issue by ChrisHill8** [phi-grib/flame#130]
When setting random_state to None in the parameters file for building a model, I get this error:
![Error when random_state is set to None](https://user-images.githubusercontent.com/44038602/54906118-e6025a00-4ee2-11e9-8472-4cc05f241a55.png)

**Comment by manuelpastor** [comment]
I was unable to reproduce in the latest version. Please update.

**Comment by manuelpastor** [comment]
Bug has been fixed in the latest version
