### ISSUE TITLE
Control the version of libraries

### ISSUE THREAD

**Issue by IgnacioPasamontes** [phi-grib/flame#141]
We have check that creating a same model produces different results depending on which version of the main packages installed (scipy, numpy, scikitlearn etc..).This does not produce an error but  can cause a misunderstanding in the user. 

Example :  

A user imports a model that has been builded in an enviromnent with different package version. This user re-build the model with the same parameters. This user obtain differents validations results all and that  tha parameters are the same.

Solutions:

- A versions control of the main flame packages that have been installed in the environment. In the same way we have a config file with the models path, we can create a version file with the versions of the main packages. 
- We also could create a hash of the packages to check it in a quickly way just to alert the user that the model that is being imported has been trainen with different packages version.

Open to discussion

**Comment by manuelpastor** [comment]
Fixed in the last Flame versions. The library versions of rdkit, scikitlearn, non-conformist and flame are stored in the models and checked on import
