### ISSUE TITLE
action_new return path instead of name space

### ISSUE THREAD

**Issue by IgnacioPasamontes** [phi-grib/flame#150]
When We want to create a space that already exist, **action_new(space)** return the path of the spaces instead of the name of the space that already exist.

`# check if there is already a tree for this endpoint`
`    if ndir.exists():`
`       #LOG.warning(f'Endpoint {space} already exists')`
`       return False, f'Endpoint {ndir} already exists'`

**Comment by manuelpastor** [comment]
Fixed!
