### ISSUE TITLE
Scaling not performed over morgan FP at model building resulting in error at prediction

### ISSUE THREAD

**Issue by josecarlosgomezt** [phi-grib/flame#172]
This statement prevents Flame from creating the scaler.

` if self.param.getVal('modelAutoscaling') and 
                        not isFingerprint:`

When using the created model for prediction, the scaler
is not found resulting in error.

**Comment by manuelpastor** [comment]
Fixed. Right now the scaling is only prevented in similarity searches using fingerprints but not for fingerprints used in predictive models
