### ISSUE TITLE
Data scaling on ensemble models control

### ISSUE THREAD

**Issue by josecarlosgomezt** [phi-grib/flame#174]
Ensemble models does not create pre-processing pickle at building which results in error at prediction. Error control is suggested until pre-processing unit is implemented for this type of models.

**Comment by manuelpastor** [comment]
Does not reproduce. learn.py makes a call to preprocess (where the preprocessing pickle is created) before instantiate the learner. No matter which kind of model is used, the preprocesssing pickle is created.
