### ISSUE TITLE
Warning colours

### ISSUE THREAD

**Issue by PARODBE** [phi-grib/flame#204]
Hi everyone,

Since all warnings appear in red, it would be much more practical to split them into three groups labelled with separated colours. For instance: green can be used for  success, orange for warnings and red for problems.

Karolina Kopanska and Pablo Rodríguez

**Comment by manuelpastor** [comment]
success is never shown as warning and toasters are shown in green. Warnings are shown in light red (sort of pink), not red. Errors are only shown in toasters, in bright red
