### ISSUE TITLE
Error when serializing data in odata.py in predict for qualitative endpoints.

### ISSUE THREAD

**Issue by josecarlosgomezt** [phi-grib/flame#34]
Both JSON and TSV data serialization fails.

JSON serialization fails when dumping the variable values from results. values is given as np.int64 type which is not compatible. 

TSV instead, fails at (line 139):
                  
```
    if isinstance(val, float):
       line += "%.4f" % val
    else:
       line += val
```

As there is no assertion for np.int64 type, the variable is not converted to string.

**Comment by manuelpastor** [comment]
I have been unable to reproduce it. Could you please provide further information about the conditions in which this bug was observed?

**Comment by manuelpastor** [comment]
PLSDA changed. Tested OK. Issue closed
