### ISSUE TITLE
very slow calculation in model building or prediction in Windows 10

### ISSUE THREAD

**Issue by manuelpastor** [phi-grib/flame#38]
When building or applying models, the program takes much more time (x10 or more) to finish in Windows than in Linux. The CPU was not in use. The problem reproduces in different Windows installs, but not in VMs

**Comment by manuelpastor** [comment]
The problem seems to be related with the handling of multiprocessing in numpy/scitkitlearn

It was discussed here
https://github.com/scikit-learn/scikit-learn/issues/10533#issuecomment-360981152
and here
http://scikit-learn.org/stable/faq.html#why-do-i-sometime-get-a-crash-freeze-with-n-jobs-1-under-osx-or-linux

The simplest workaround is to avoid multiprocessing by replacing  n_jobs=-1 with n_jobs=1 (no value but 1 seems to solve the problem)

We plan to test other suggested workarounds

**Comment by BielStela** [comment]
@manuelpastor  wasn't this an issue with sklearn's `n_jobs` unrelated to flame?

**Comment by jamescporter** [comment]
Is there any work around now?
