### ISSUE TITLE
Use Pathlib to handle the paths

### ISSUE THREAD

**Issue by BielStela** [phi-grib/flame#4]
Since we are using python 3.6 we could get advantage of the new [pathlib](https://docs.python.org/3/library/pathlib.html) (new since 3.4). Its standard library to work with path (either posix or windows) with a lot of useful methods. Since we are dealing with multiple sdfiles (when working with cpu>1) it will be helpfull!

**Comment by manuelpastor** [comment]
In my opinion pathlib is not more readable than os.path. What should be avoided is the use of string operations (eg. "filename"+"/"+".ext") to ensure compatibility across platforms

**Comment by manuelpastor** [comment]
Pathlib will NOT be adopted generally, only in cases when it adds something in terms of readability
