### ISSUE TITLE
Loading and dumping of YAML file with ordered dict

### ISSUE THREAD

**Issue by BielStela** [phi-grib/flame#52]
Use [yamlloader](https://github.com/Phynix/yamlloader) to load and write the YAML with ordered dict so it maintains the order.

**Comment by manuelpastor** [comment]
Good idea! Please update flame environment and replace yaml (in utils) with this

**Comment by manuelpastor** [comment]
This suggestion has become obsolete since we adopted a more sophisticated parameter file which is not handled manually
