### ISSUE TITLE
Molecule standardization wrong behavior in workflow_series

### ISSUE THREAD

**Issue by josecarlosgomezt** [phi-grib/flame#54]
When standardizing a molecule series, if one molecule fails in the standardization process, the whole series is rejected.

```
                if 'standardize' in method:
                    try:
                        parent = standardise.run(Chem.MolToMolBlock(m))
                    except standardise.StandardiseException as e:
                        if e.name == "no_non_salt":
                            parent = Chem.MolToMolBlock(m)
                        else:    **--> then the function is returning False for the whole series**
                            return False, e.name
                    except:
                        return False, "Unknown standardiser error"
```

Flame is returning the error message: "False {"error": "number of molecules informed and processed does not match"} " as no molecule could be processed.

**Comment by manuelpastor** [comment]
So far, flame is creating a list of molecules processed OK/failed only at the last step of the molecular workflow (MD computation). The same concept must be extended to all steps of the workflow. Therefore, a failure to standardise a molecule will only remove this molecule and not all the series.

An effort to improve and simplifying error handling is ongoing

**Comment by josecarlosgomezt** [comment]
Any other exception different to "no_non_salt" will break the workflow with error in the number of molecules informed when molecules series is used.
"return" statements should be removed and replaced by  a success list as made in other steps in the workflow.

**Comment by josecarlosgomezt** [comment]
Done
