### ISSUE TITLE
Subsampling

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#65]
I don't know if this is useful but:
- I would really appreciate to have the dataset in SD format after subsampling is done. 
- I would like to choose another the random seed to generate the samples, to be reproducible afterwards, and play with different ones.

**Comment by josecarlosgomezt** [comment]
Sampling now is done in X and Y matrices so it should be implemented in a different place. Perhaps in utils.

I agree with respect to the random seed, but with concerns about the increasing number of parameters.
