### ISSUE TITLE
OUTPUT formats

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#68]
Molecular descriptors:
-It creates a file with the same name for both build and predict.  I would recommend to put different names. 

Build:
- It always gives JSON output format 
- Maybe need TSV format
- Recalculated values does not appers
- subsampling: creates a new dataset that is not saved anywhere. I would really appreciate if it could be saved in the model folder. 
-JSON output: it does not give you the recalculated values, when running without conformal. when running conformal, it does not give you the upper and lower limit values, as it is shown in the predict part. 
-It would be good to have plots ( scatters, ... )

Predict:
- JSON output: I would  give the same output as the one given in Build section, with Q2, SDEP, .... in the first lines. 
- TSV output: I would add quality parameters such as sens, spec, mcc, coverage, accuracy,  q2, SDEP, ...
- plots (scatters, ...)

Could it be possible to obtain a table where appears:

MD |  spec_calc | sens_calc | MCC_calc | spec_CV | sens_CV | MCC_CV | Coverage_CV | Accuracy_CV | spec_extv | sens_extv | MCC_extv | Coverage_extv
RDKit_properties |   |   |   | 0.77 | 0.79 | 0.55 | 0.47 | 0.78 | 0.74 | 0.58 | 0.32 | 0.51
RDKit_md |   |   |   | 0.78 | 0.73 | 0.50 | 0.36 | 0.75 | 0.79 | 0.80 | 0.58 | 0.48

**Comment by bet-gregori** [comment]
I would suggest to change the headers to something more intuitive. Currently the header is:
- obj_nam
- SMILES
- c0: Boolean (?)
- c1: Boolean (?)
- ymatrix: Float. In theory predicted activity (see https://github.com/phi-grib/flame/issues/88)

**Comment by bet-gregori** [comment]
After checking the code, I understand that c0 is whether the compound is redicted to be negative and c1 is whether the compound is predicted to be positive. This would need to be documented (see #90). 
ymatrix is in fact not the predicted activity as I thought but the value in the MANDATORY activity field in the query SD file (#88)
