### ISSUE TITLE
descriptors matrix `xmatrix` building routine must be rewrited

### ISSUE THREAD

**Issue by BielStela** [phi-grib/flame#74]
Now it build the matrix row by row and it's hard to read and has very poor perfomance. We must change it to a more canonical way like filling the matrix from a preallocated empty one (like np.zeros).

Here you have a notebook example where I explore the matrix building routines. 

https://gist.github.com/BielStela/a856da5aa75836cee06e87a3b380d872

**Comment by manuelpastor** [comment]
The rows are now pre-allocated in compute_md to improve performance
