### ISSUE TITLE
`Control` class should be a set of functions?

### ISSUE THREAD

**Issue by BielStela** [phi-grib/flame#81]
`control.py` class `Control` shouldn't be a class since it doesn't use any state given by the instance and all the functions could use model name as parameter. The functions could be in `utils.py`.

This way we will remove a module and reduce the whole code base complexity and readability.

**Comment by manuelpastor** [comment]
Control class was required to run networks of models. This is an advanced feature which will require furether documentation. In any case, it is not a priority, so please wait

**Comment by manuelpastor** [comment]
After reviewing the code I agree that this class is not needed. It has been replaced by a simple "get_parameters" function in utils
