### ISSUE TITLE
Result JSON from action_info should return the predict and original matrix

### ISSUE THREAD

**Issue by Javimuca** [phi-grib/flame#84]
The model built result on a quantitative model should return the predicted matrixes to do scatter plots.

**Comment by Javimuca** [comment]
The change was done to get additional data from info.pkl, it was dumping the model on a wrong way, making it unavailable to retrieve the model data (TN, TP, FP, FN, etc)

**Comment by manuelpastor** [comment]
It was easy yo pass Y adjusted and Y predicted (CV) in the results for non-conformal models. Now, these are printed. Encapsulating everything in a JSON requires some more work, but is perfectly feasible
