### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by bet-gregori** [phi-grib/flame#90]
Needs extensive documentation of the options in the parameters.yaml file. For instance, in the fields with controlled vocabulary (i.e. ModelValidationCV), include the list and description of the options available.

Also needed is an explanation of the output file (see https://github.com/phi-grib/flame/issues/68#issuecomment-445824861) and what each column means. Additionally, it would be good to know in qualitative models what True/True (for c0 and c1) means.

**Comment by manuelpastor** [comment]
The need of documenting the yaml file is obvious. All acceptable options for entries with controlled vocabularies are already documented.
Output related issues were already mentioned in other issues (#68, for example )
