### ISSUE TITLE
Building model error: Kbest parameters yaml error and conformal

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#93]
When Kbest is set in parameters.yaml file, the following error appears me. 

flame -c build -e BioTF-RF -f ../0-randomsplit/trainingSet/tr-BioTF.sdf 
INFO - Starting building model BioTF-RF with file ../0-randomsplit/trainingSet/tr-BioTF.sdf
/home/kpinto/miniconda3/envs/kpi36/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
INFO - Recycling data from /phi/users/kpinto/flame_models/BioTF-RF/dev/data.pkl
INFO - Building model using internal toolkit : Sci-kit learn
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.

**Comment by kpinto-gil** [comment]
When Kbest is not used the following error is shown:
/home/kpinto/miniconda3/envs/kpi36/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
INFO - Running with input type: molecule
INFO - Computing molecular descriptors with methods ['RDKit_md']...
INFO - Computing RDKit descriptors...
INFO - Building model using internal toolkit : Sci-kit learn
tune_parameters
metric: r2
best parameters:  {'max_features': 'sqrt', 'n_estimators': 25, 'oob_score': True, 'random_state': 46}
found in:  76.71754193305969  seconds
Traceback (most recent call last):
  File "/home/kpinto/miniconda3/envs/flame/bin/flame", line 11, in <module>
    load_entry_point('flame', 'console_scripts', 'flame')()
  File "/phi/users/kpinto/flame/flame/flame_scr.py", line 184, in main
    success, results = context.build_cmd(model)
  File "/phi/users/kpinto/flame/flame/context.py", line 160, in build_cmd
    success, results = build.run(lfile)
  File "/phi/users/kpinto/flame/flame/build.py", line 98, in run
    results = learn.run()
  File "/phi/users/kpinto/flame/flame/learn.py", line 140, in run
    self.run_internal()
  File "/phi/users/kpinto/flame/flame/learn.py", line 103, in run_internal
    success, results = model.validate()
  File "/phi/users/kpinto/flame/flame/stats/base_model.py", line 388, in validate
    success, results = self.CF_quantitative_validation()
  File "/phi/users/kpinto/flame/flame/stats/base_model.py", line 161, in CF_quantitative_validation
    random_state=i, shuffle=False)
  File "/home/kpinto/miniconda3/envs/kpi36/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 1684, in train_test_split
    raise TypeError("Invalid parameters passed: %s" % str(options))
TypeError: Invalid parameters passed: {'shuffle': False}

**Comment by BielStela** [comment]
@kpinto-gil  para el primer comentario, prueba de reinstalar Numpy

**Comment by BielStela** [comment]
Y también pruebo de hacer un update de scikit-learn a ver si tienes un versión antigua donde `train_test_split` no tiene el parámetro `shuffle`

**Comment by kpinto-gil** [comment]
The bug was in numpy and scikit versions. Even trying updating, still it was appearing the same shuffle error. So I uninstall scikit learn and realized that there were two versions of scikit learn. So I uninstall  and installed everything again,  and suprised, it worked.
