### ISSUE TITLE
data.pkl prediction

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#94]
Running a prediction like this:
`flame -c predict -e BioTF-RF -f ../0-randomsplit/predictionSet/pr-BioTF.sdf`
data.pkl file is saved in the same path as the prediction set was. Should data.pkl file be removed or saved in the same path I am running flame command?

**Comment by manuelpastor** [comment]
By design, the data.pkl is saved in the same path of the original file. This allows preventing overwritting pickles for different files
